import { NextApiResponse } from 'next'

export default (req: any, res: NextApiResponse) => {
    res.status(200).json([
        {
            name: "NicoCommeDon",
            thumbnail: "https://shared-vps.compositecomputer.club/media/images/system/asset-1.png",
            genre: "デスクトップアプリ",
            description: "ニコニコのコメントみたいにマストドンのトゥートが流れるLTサポートツール．WindowsとLinuxに対応．",
            url: "https://qiita.com/PigeonsHouse/items/2ec02d570e0c8be69ae5",
            download_url: "https://github.com/PigeonsHouse/NicoCommeDon/releases/",
            source_url: "https://github.com/PigeonsHouse/NicoCommeDon",
            created_at: "2021年1月〜8月",
        },
        {
            name: "Magic Adventure(共同制作)",
            thumbnail: "https://raw.githubusercontent.com/PigeonsHouse/red-action/master/Assets/Sprites/OP.png",
            genre: "ゲーム",
            description: "C3の部員との共同制作．初めてきちんと完成させたゲーム．",
            url: "https://unityroom.com/games/magic_action_game_c3",
            download_url: null,
            source_url: null,
            created_at: "2020年5月〜7月",
        },
        {
            name: "水嵩 ﾐｽﾞｶｻ",
            thumbnail: "https://raw.githubusercontent.com/PigeonsHouse/Mizukasa/main/%E3%82%B5%E3%83%A0%E3%83%8D.png",
            genre: "ゲーム",
            description: "UnityRoom主催の1WeekGameJamでの作品．初めて一人で作ったゲーム．",
            url: "https://unityroom.com/games/vow_game_pigeon-house",
            download_url: null,
            source_url: "https://github.com/PigeonsHouse/Mizukasa",
            created_at: "2020年8月",
        },
        {
            name: "RSA暗号特設サイト",
            thumbnail: "https://pbs.twimg.com/media/E7YqUEiVkAAqbqE.png",
            genre: "Webサイト",
            description: "某YoutuberのRSA暗号の解説動画に興味を持ち作成．解説と同じ手順で暗号化・復号ができるサイト．",
            url: "https://rsa-qk.pigeons.house",
            download_url: null,
            source_url: "https://github.com/PigeonsHouse/rsa_qk",
            created_at: "2021年7月",
        },
        {
            name: "進捗ちゃんBot",
            thumbnail: "https://cdn.discordapp.com/avatars/821046992460316733/59f462a6e76bf3a3d15e7c476c7aec5b.png",
            genre: "DiscordBot",
            description: "Discord上で作業の開始・終了を宣言すると時間を計測して進捗を記録してくれるBot．月始めに先月の総作業量を報告してくれる．",
            url: "https://qiita.com/PigeonsHouse/items/9d86e35dbb6550d8f853",
            download_url: "https://discord.com/api/oauth2/authorize?client_id=821046992460316733&permissions=0&scope=bot",
            source_url: "https://github.com/PigeonsHouse/sintyokuBot",
            created_at: "2021年3,4月",
        },
        {
            name: "ロックマン.EXE Bot",
            thumbnail: "https://mastodon.compositecomputer.club/system/accounts/avatars/000/002/398/original/8d44cff7b58e9ae0.png",
            genre: "MastodonBot",
            description: "C3部内のSNS，Mastodon内で稼働しているBot．C3部員の生活に役立ったり立たなかったりする機能が搭載している．",
            url: "https://mastodon.compositecomputer.club/@Rockmanexe",
            download_url: null,
            source_url: null,
            created_at: "2020年9月",
        },
        {
            name: "0.0046%の確率でポケモンを捕まえるサトシBot",
            thumbnail: "https://mastodon.compositecomputer.club/system/accounts/avatars/000/004/289/original/66d097ff94b6995f.jpg",
            genre: "MastodonBot",
            description: "C3部内のSNS，Mastodon内で稼働しているBot．Botの名前の通り．約2.5ヶ月に1度ポケモンをゲットする確率になっている．",
            url: "https://mastodon.compositecomputer.club/@pokeget",
            download_url: null,
            source_url: null,
            created_at: "2021年1月",
        },
        {
            name: "鳩屋敷Bot",
            thumbnail: "https://mastodon.compositecomputer.club/system/accounts/avatars/000/005/580/original/aef9c28c66c78da4.png",
            genre: "MastodonBot",
            description: "製作者である鳩屋敷の投稿を全て学習させ鳩屋敷っぽい投稿をするBot．深層学習に興味を持ち，GPT2のファインチューニングで試しに作ってみた．",
            url: "https://mastodon.compositecomputer.club/@hatoBot",
            download_url: null,
            source_url: null,
            created_at: "2021年6月",
        },
    ]);
}
